baseURL = "http://example.org/"
languageCode = "en-us"
title = "Josh's Tech Blog"
theme = "base16"
pygmentsuseclasses = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
MetaDataFormat = "toml"
[taxonomies]
    tag = "tags"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
