baseURL = "https://www.yhkaplan.com"
languageCode = "en-us"
title = "Josh's Tech Blog"
theme = "m10c"
canonifyurls = true
paginate = 10
# pygmentsUseClasses = true
pygmentsCodeFences = true

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  author = "Josh Kaplan"
  description = "iOS developer and aspiring backend developer"
  avatar = "https://avatars3.githubusercontent.com/u/25879490?s=400&v=4"
  # avatar = "static/assets/images/profile.jpeg"
  subtitle = "A Hugo Theme"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  [[params.social]]
    name = "github"
    url = "https://github.com/yhkaplan"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/yhkaplan"
